export const DEFAULT_TIPOS_OC = [
  { value: '', label: 'Seleccione...' },
  { value: '14', label: 'OBRA' },
  { value: '2', label: 'PRODUCCION' },
  { value: '1', label: 'CORPORATIVO' },
  { value: '19', label: 'MANTENIMIENTO' },
  { value: '9', label: 'IGLESIA' },
  { value: '153', label: 'LOGISTICA' },
  { value: '0', label: 'RENTA DE EQUIPO' },
]

export const DEFAULT_EMPRESAS = [
  { value: '', label: 'Seleccione...' },
  { value: '17', label: 'INSTALACIONES TECNOLOGICAS APLICADAS SA DE CV' },
  { value: '2', label: 'INSTALACIONES Y TECNICA SA DE CV' },
  { value: '12', label: 'CANALIZACION Y SOPORTERIA MEXICANA SA DE CV' },
  { value: '9', label: 'INMOBILIARIA EGUEL SA DE CV' },
  { value: '3', label: 'DEL TERCER DIA AC' },
  { value: '6', label: 'LA IGLESIA DEL TERCER DIA AR' },
  { value: '15', label: 'INMOBILIARIA DEL REINO LI3D SA DE CV' },
  { value: '16', label: 'INMOBILIARIA BARRIO 18 SA DE CV' },
  { value: '1', label: 'INDUSTRIAL CONNECT MEXICO S DE RL DE CV' },
  { value: '0', label: 'MOVIMIENTO CONTINUO SA DE CV' },
  { value: '19', label: 'SUIL & ODRAUDE SC' },
  { value: '4', label: 'EDUARDO PADILLA URANGA' },
  { value: '7', label: 'I' },
]

export const DEFAULT_CONDICIONES = [
  { value: '', label: 'Seleccione...' },
  { value: '1', label: 'CONTADO' },
  { value: '9', label: 'REEMBOLSO' },
  { value: '3', label: 'FINIQUITO' },
  { value: '2', label: '8 DIAS' },
  { value: '106', label: '14 DIAS' },
  { value: '12', label: '15 DIAS' },
  { value: '10', label: '20 DIAS' },
  { value: '157', label: '26 DIAS' },
  { value: '5', label: '28 DIAS' },
  { value: '11', label: '30 DIAS' },
  { value: '18', label: '45 DIAS' },
  { value: '8', label: '60 DIAS' },
  { value: '15', label: '120 DIAS' },
  { value: '16', label: 'ANTICIPO 10%' },
  { value: '4', label: 'ANTICPO 30%' },
  { value: '7', label: 'ANTICIPO 50%' },
  { value: '153', label: 'ANTICIPO 60%' },
  { value: '0', label: 'ANTICIPO 65%' },
  { value: '14', label: 'ANTICIPO 70%' },
  { value: '108', label: 'TARJETA DE CREDITO' },
  { value: '6', label: 'PAGO SEMESTRAL' },
  { value: '13', label: 'PAGO MENSUAL' },
  { value: '19', label: 'COMPRA EN LINEA' },
  { value: '17', label: 'N/A' },
]

